version: "3"
services:
  backend:
    build: ./backend
    environment:
      PORT: 8080
      DB_HOST: mysql
    ports:
      - 8080:8080
    volumes:
    - ./backend:/app
  mysql:
    image: mysql:5.7
    command: --default-authentication-plugin=mysql_native_password --character-set-server=utf8mb4
      --collation-server=utf8mb4_unicode_ci
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
      MYSQL_DATABASE: test
      MYSQL_PASSWORD: test
      MYSQL_USER: test
    ports:
    - 3306:3306
