spring:
  datasource:
    url: jdbc:mysql://${DB_HOST:localhost}:3306/test?serverTimezone=Asia/Tokyo
    username: test
    password: test
    driverClassName: com.mysql.jdbc.Driver
    initialization-mode: always

# mybatis:
#  mapper-locations: classpath*:/mybatis/mapper/*.xml
#  type-aliases-package: com.example.sample.model
#  configuration:
#    map-underscore-to-camel-case: true
#    default-fetch-size: 100
#    default-statement-timeout: 30
#    cache-enabled: false
